version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medichain
    ports: ['3306:3306']
    volumes:
      - mysql_data:/var/lib/mysql
  mongo:
    image: mongo:6.0
    ports: ['27017:27017']
    volumes:
      - mongo_data:/data/db
volumes:
  mysql_data:
  mongo_data:
