openapi: 3.0.1
info:
  title: MediChain API
  version: 0.1.0
paths:
  /patient/{id}:
    get:
      summary: Get patient record
      parameters:
        - name: id
          in: path
          required: true
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
